# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestloginadmin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testloginadmin(self):
    self.driver.get("http://127.0.0.1:8000/login")
    self.driver.set_window_size(1518, 804)
    self.driver.find_element(By.ID, "exampleInputEmail").click()
    self.driver.find_element(By.ID, "exampleInputEmail").send_keys("admin@gmail.com")
    self.driver.find_element(By.ID, "exampleInputPassword").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".d-lg-inline-block").text == "Hi, Admin"
  
