# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestloginstaff():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testloginstaff(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.find_element(By.ID, "exampleInputEmail").send_keys("krisandromartinus@gmail.com")
    self.driver.find_element(By.ID, "exampleInputPassword").send_keys("sandro123abc")
    self.driver.find_element(By.ID, "exampleInputEmail").click()
    self.driver.find_element(By.ID, "exampleInputEmail").send_keys("staff@gmail.com")
    self.driver.find_element(By.ID, "exampleInputPassword").send_keys("staff")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.LINK_TEXT, "Hi, Staff").text == "Hi, Staff"
  
