# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTeststaffstockin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_teststaffstockin(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".has-dropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Stock In").click()
    self.driver.find_element(By.LINK_TEXT, "New Track").click()
    self.driver.find_element(By.ID, "quantity").click()
    self.driver.find_element(By.ID, "quantity").send_keys("1")
    self.driver.find_element(By.ID, "received_at").click()
    self.driver.find_element(By.ID, "received_at").click()
    self.driver.find_element(By.ID, "received_at").send_keys("2024-06-27T22:30")
    self.driver.find_element(By.CSS_SELECTOR, ".card-body > form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
